export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_SELECTED_TYPE = "SET_SELECTED_TYPE";

export const SET_SELECTED_CITY = "SET_SELECTED_CITY";

export const SET_ENTERED_TEXT = "SET_ENTERED_TEXT";

export const GET_ENABLED_TYPES_START = "GET_ENABLED_TYPES_START";
export const GET_ENABLED_TYPES_SUCCESS = "GET_ENABLED_TYPES_SUCCESS";
export const GET_ENABLED_TYPES_FAIL = "GET_ENABLED_TYPES_FAIL";

export const GET_FILTERED_RESULTS_START = "GET_FILTERED_RESULTS_START";
export const GET_FILTERED_RESULTS_SUCCESS = "GET_FILTERED_RESULTS_SUCCESS";
export const GET_FILTERED_RESULTS_FAIL = "GET_FILTERED_RESULTS_FAIL";

export const GET_OBJECT_TYPES_START = "GET_OBJECT_TYPES_START";
export const GET_OBJECT_TYPES_SUCCESS = "GET_OBJECT_TYPES_SUCCESS";
export const GET_OBJECT_TYPES_FAIL = "GET_OBJECT_TYPES_FAIL";

export const GET_CITIES_START = "GET_CITIES_START";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_FAIL = "GET_CITIES_FAIL";

export const RESET_FILTERS = "RESET_FILTERS";
